import { notFound } from "next/navigation";
import Link from "next/link";
import { Topbar } from "@/components/shell/Topbar";
import { Card } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { can } from "@/lib/auth/permissions";
import { requireSession } from "@/lib/data/session";
import { listEmailLog } from "@/lib/data/emailData";
import { emailConfigured } from "@/lib/email/resend";
import { formatDateTime } from "@/lib/format";
import { ManualEmailForm } from "@/components/email/ManualEmailForm";
import { EmailAutomationManager } from "@/components/email/EmailAutomationManager";
import { listEmailRules } from "@/lib/data/settingsData";

export const dynamic = "force-dynamic";

const STATUS_META: Record<string, { cls: string }> = {
  sent: { cls: "bg-emerald-100 text-emerald-700" },
  queued: { cls: "bg-blue-100 text-blue-700" },
  failed: { cls: "bg-red-100 text-red-700" },
  skipped: { cls: "bg-line-faint text-ink-500" },
};

/**
 * Emails log (§D). Shows every email the application generated with the real
 * provider outcome — never a fabricated delivery status. Configure `RESEND_API_KEY`
 * to enable actual sending; without it, rule dispatches are logged as "skipped".
 */
export default async function EmailsPage() {
  const { effective: user } = await requireSession();
  if (!can(user.role, "email.view")) notFound();

  const [rows, rules] = await Promise.all([listEmailLog(), listEmailRules()]);
  const configured = emailConfigured();

  return (
    <>
      <Topbar title="Emails" />
      <div className="flex-1 overflow-auto px-[18px] py-4">
        <EmailAutomationManager rules={rules} canManage={can(user.role, "email.manage")} />
        <ManualEmailForm />
        {!configured && (
          <div className="mb-3 rounded-control border border-amber-200 bg-amber-50 px-3 py-2 text-[11.5px] text-amber-800">
            Resend is not configured (<span className="font-mono">RESEND_API_KEY</span> is unset). Rule dispatches are
            recorded as <span className="font-semibold">skipped</span> until a key is added.
          </div>
        )}

        {rows.length === 0 ? (
          <EmptyState
            title="No emails yet"
            hint="Emails generated by automation rules (booking created, overdue summary, custom rules) will appear here."
          />
        ) : (
          <Card className="overflow-x-auto">
            <table className="w-full min-w-[840px] text-[12px]">
              <thead>
                <tr className="border-b border-line-soft text-left text-[11px] font-semibold uppercase tracking-wide text-ink-400">
                  <th className="px-3 py-2">When</th>
                  <th className="px-3 py-2">Recipients</th>
                  <th className="px-3 py-2">Subject</th>
                  <th className="px-3 py-2">Rule / trigger</th>
                  <th className="px-3 py-2">Lead</th>
                  <th className="px-3 py-2">Status</th>
                  <th className="px-3 py-2">Provider / error</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => {
                  const sm = STATUS_META[r.status] ?? STATUS_META.queued;
                  return (
                    <tr key={r.id} className="border-b border-line-faint align-top">
                      <td className="whitespace-nowrap px-3 py-2 text-ink-600">{formatDateTime(r.createdAt)}</td>
                      <td className="px-3 py-2 text-ink-800">
                        {r.recipients.length ? r.recipients.join(", ") : <span className="text-ink-400">—</span>}
                      </td>
                      <td className="px-3 py-2 text-ink-900">{r.subject ?? "—"}</td>
                      <td className="px-3 py-2">
                        <div className="font-medium text-ink-700">{r.ruleKey ?? "—"}</div>
                        <div className="font-mono text-[10.5px] text-ink-400">{r.trigger ?? ""}</div>
                      </td>
                      <td className="px-3 py-2">
                        {r.leadHumanId ? (
                          <Link href={`/leads/${r.leadHumanId}`} className="font-mono text-[11px] font-semibold text-primary hover:underline">
                            {r.leadHumanId}
                          </Link>
                        ) : (
                          <span className="text-ink-400">—</span>
                        )}
                      </td>
                      <td className="px-3 py-2">
                        <span className={`rounded-pill px-2 py-0.5 text-[10px] font-semibold ${sm.cls}`}>{r.status}</span>
                      </td>
                      <td className="px-3 py-2 text-[11px] text-ink-500">
                        {r.providerMessageId && <div className="font-mono">{r.providerMessageId}</div>}
                        {r.error && <div className="text-red-600">{r.error}</div>}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </Card>
        )}
      </div>
    </>
  );
}
